package cn.com.syzg.repository;

import cn.com.syzg.model.Emply;
import java.util.List;

public interface EmplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emply
     *
     * @mbg.generated
     */
    int insert(Emply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emply
     *
     * @mbg.generated
     */
    List<Emply> selectAll();
}